# Spring LDAP Mapping Attributes to POJO with AttributesMapper configuration application.yml

spring:

  ldap:
    # Embedded Spring LDAP
    embedded:
      base-dn: 'dc=springframework,dc=org'
      credential:
        username: uid=admin,ou=people,dc=springframework,dc=org
        password: secret
      ldif: classpath:schema.ldif
      url: ldap://localhost:8389/
      port: 8389
      validation:
        enabled: false

  thymeleaf:
    cache: false

  security:
    user:
      name: admin
      password: secret